# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: idm_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'idm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11idm_service.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"F\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"2\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"T\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"6\n\x12\x43reateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"h\n\x15\x43hangePasswordRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x18\n\x10\x63urrent_password\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\":\n\x16\x43hangePasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x11\x44\x65leteUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"6\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd0\x02\n\nIDMService\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12>\n\rValidateToken\x12\x15.ValidateTokenRequest\x1a\x16.ValidateTokenResponse\x12)\n\x06Logout\x12\x0e.LogoutRequest\x1a\x0f.LogoutResponse\x12\x35\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\x12\x35\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\x12\x41\n\x0e\x43hangePassword\x12\x16.ChangePasswordRequest\x1a\x17.ChangePasswordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=21
  _globals['_LOGINREQUEST']._serialized_end=71
  _globals['_LOGINRESPONSE']._serialized_start=73
  _globals['_LOGINRESPONSE']._serialized_end=103
  _globals['_VALIDATETOKENREQUEST']._serialized_start=105
  _globals['_VALIDATETOKENREQUEST']._serialized_end=142
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=144
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=214
  _globals['_LOGOUTREQUEST']._serialized_start=216
  _globals['_LOGOUTREQUEST']._serialized_end=246
  _globals['_LOGOUTRESPONSE']._serialized_start=248
  _globals['_LOGOUTRESPONSE']._serialized_end=298
  _globals['_CREATEUSERREQUEST']._serialized_start=300
  _globals['_CREATEUSERREQUEST']._serialized_end=384
  _globals['_CREATEUSERRESPONSE']._serialized_start=386
  _globals['_CREATEUSERRESPONSE']._serialized_end=440
  _globals['_CHANGEPASSWORDREQUEST']._serialized_start=442
  _globals['_CHANGEPASSWORDREQUEST']._serialized_end=546
  _globals['_CHANGEPASSWORDRESPONSE']._serialized_start=548
  _globals['_CHANGEPASSWORDRESPONSE']._serialized_end=606
  _globals['_DELETEUSERREQUEST']._serialized_start=608
  _globals['_DELETEUSERREQUEST']._serialized_end=645
  _globals['_DELETEUSERRESPONSE']._serialized_start=647
  _globals['_DELETEUSERRESPONSE']._serialized_end=701
  _globals['_IDMSERVICE']._serialized_start=704
  _globals['_IDMSERVICE']._serialized_end=1040
# @@protoc_insertion_point(module_scope)
